---
- name: Instalando pacotes necessários
  yum:
    name: glibc-static
    state: present
    update_cache: yes

- name: Baixando o Node Exporter na versão {{ node_exporter_version }} (sha256)
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp
    checksum: "sha256:{{ hash_node_exporter }}"
  register: download

- name: Descompactando o arquivo baixado.
  unarchive:
    src: "{{ download.dest }}"
    dest: /usr/src
    remote_src: yes
  register: unpacked

- name: Copiando binário para o PATH do sistema.
  copy:
    src: "{{ unpacked.dest }}/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: /usr/bin
    owner: root
    group: root
    mode: 0755
    remote_src: yes

- name: Criando o script de inicialização do serviço.
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644

- name: Inicializando o serviço.
  systemd:
    name: node_exporter.service
    state: started
    enabled: yes