---
- name: Criando o usuário {{ node_exporter_user }}.
  user:
    name: "{{ node_exporter_user }}"
    comment: Prometheus Node Exporter
    shell: /sbin/nologin
    state: present
    create_home: no